# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agregado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proveedor', models.CharField(max_length=20)),
                ('nombre_banco', models.CharField(max_length=20)),
                ('n_cta', models.CharField(max_length=20, unique=True)),
                ('tipo_cta', models.CharField(choices=[('Ahorro', 'Ahorro'), ('Corriente', 'Corriente')], max_length=20, null=True)),
                ('observacion', models.TextField(null=True)),
                ('fecha_ag', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('n_cta', models.CharField(max_length=20, unique=True)),
                ('fecha_b', models.DateField(null=True)),
                ('agregados', models.ManyToManyField(to='cuentas.Agregado')),
            ],
        ),
    ]
